{
 "title": "Materialize Overview",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "command",
    "query": "label_values(mz_command_durations_bucket, command)"
   },
   {
    "name": "client_query",
    "label": "Client queries",
    "query": "label_values(mz_client_peek_seconds_hist, query)"
   },
   { "name": "build_info", "label": "Build Info", "query": "--->" },
   {
    "name": "built_at",
    "label": "Built at",
    "query": "label_values(mz_server_metadata_seconds, build_time)"
   },
   {
    "name": "build_version",
    "label": "Version",
    "query": "label_values(mz_server_metadata_seconds, build_version)"
   },
   {
    "name": "build_sha",
    "label": "Git commit",
    "query": "label_values(mz_server_metadata_seconds, build_sha)"
   }
  ]
 },
 "panels": [
  { "title": "Queries", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "command=$command server latency heatmap",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(mz_command_durations_hist{command=~\"$command\",status=\"success\"}[10s])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "command=$command server latency quantiles",
   "type": "graph",
   "description": "the view of how long things took, from inside pgwire",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(1, sum(rate(mz_command_durations_bucket{command=~\"$command\",status=\"success\"}[30s])) by (le))",
     "legendFormat": "max"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(mz_command_durations_bucket{command=~\"$command\",status=\"success\"}[30s])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(mz_command_durations_bucket{command=~\"$command\",status=\"success\"}[30s])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(mz_command_durations_bucket{command=~\"$command\",status=\"success\"}[30s])) by (le))",
     "legendFormat": "median"
    },
    {
     "expr": "histogram_quantile(0.001, sum(rate(mz_command_durations_bucket{command=~\"$command\",status=\"success\"}[30s])) by (le))",
     "legendFormat": "p001"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(mz_command_durations_bucket{command=~\"$command\",status=\"error\"}[30s])) by (le))",
     "legendFormat": "error p99"
    },
    {
     "expr": "histogram_quantile(1, sum(rate(mz_command_durations_bucket{command=~\"$command\",status=\"error\"}[30s])) by (le))",
     "legendFormat": "error max"
    }
   ]
  },
  {
   "title": "queries/second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "rate(mz_command_durations_count[2s])",
     "legendFormat": "{{command}}"
    }
   ]
  },
  {
   "title": "query rows|bytes/second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    { "expr": "rate(mz_pg_sent_rows[10s])", "legendFormat": "rows/sec" },
    { "expr": "rate(mz_pg_sent_bytes[10s])", "legendFormat": "bytes/sec" }
   ]
  },
  { "title": "Ingest", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Frontier lags",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "ms", "label": "Lag (from -> to)" }
   ],
   "targets": [
    {
     "expr": "topk(10, mz_perf_dependency_frontiers)",
     "legendFormat": "{{source}} -> {{dataflow}}"
    }
   ]
  },
  {
   "title": "Worker queue sizes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mz_worker_command_queue_size",
     "legendFormat": "pending commands worker={{worker}}"
    },
    {
     "expr": "mz_worker_pending_peeks_queue_size",
     "legendFormat": "pending peeks worker={{worker}}"
    }
   ]
  },
  {
   "title": "Messages Ingested",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "rate(mz_dataflow_events_read_total[2s])",
     "legendFormat": "{{format}} events {{status}}"
    },
    {
     "expr": "mz_dataflow_events_read_total",
     "legendFormat": "{{format}} events total {{status}}"
    }
   ]
  },
  {
   "title": "Kafka bytes read",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "rate(mz_kafka_bytes_read_total[3s])",
     "legendFormat": "rate"
    },
    { "expr": "mz_kafka_bytes_read_total", "legendFormat": "total" }
   ]
  },
  {
   "title": "Messages behind external source",
   "type": "graph",
   "description": "This shows the number of messages that materialize knows it is behind an external source.\n\nFor example, if there are 1,000 messages in kafka and materialized has processed 750, this value will be 250",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mz_kafka_partition_offset_max - mz_kafka_partition_offset_ingested",
     "legendFormat": "{{topic}} (part={{partition_id}})"
    }
   ]
  },
  {
   "title": " Capability Closing Rate",
   "type": "graph",
   "description": "Rate at which capabilities are downgraded in the system",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(mz_kafka_capability[3s])", "legendFormat": "{{topic}}-{{source_id}}" }
   ]
  },
  {
   "title": "Kafka Data Ingestion Rate",
   "type": "graph",
   "description": "Rate at which data is first received from the Kafka Source",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mz_kafka_partition_offset_received",
     "legendFormat": "{{topic}}-{{source_id}}"
    }
   ]
  },
  {
   "title": "Partition Imbalance Amount",
   "type": "graph",
   "description": "Rate at which capabilities are downgraded in the system",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max by (topic, source_id) (mz_kafka_partition_closed_ts) - min by (topic, source_id) (mz_kafka_partition_closed_ts)",
     "legendFormat": "{{topic}}-{{source_id}}"
    }
   ]
  },
  {
   "title": "Timestamp Closing Lag",
   "type": "graph",
   "description": "Difference between allocated timestamps and close timestamps",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(mz_max_timestamp- ignoring(topic) mz_kafka_partition_closed_ts)",
     "legendFormat": "{{source_id}}-{{partition_id}}"
    }
   ]
  },
  {
   "title": "Time behind external source",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "mz_kinesis_shard_millis_behind_latest",
     "legendFormat": "{{ stream_name }} {{ shard_id }}"
    }
   ]
  },
  { "title": "Resource Consumption", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 58 } },
  {
   "title": "materialized: resident memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "process_resident_memory_bytes", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "materialized: CPU usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"materialized\"}[2s])",
     "legendFormat": "{{job}}"
    },
    {
     "expr": "rate(process_cpu_seconds_total{job=\"mz_client_peek\"}[30s])",
     "legendFormat": "{{job}} (doesn't show subprocesses)"
    }
   ]
  },
  {
   "title": "Arrangement Batches",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "mz_perf_arrangements_batches", "legendFormat": "w={{worker}} op={{operator}}" }
   ]
  },
  {
   "title": "Arrangement Records",
   "type": "graph",
   "description": "Uncompacted records in each arrangement",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mz_perf_arrangement_records",
     "legendFormat": "w={{worker}} op={{operator}} name={{name}}"
    }
   ]
  }
 ]
}